require: rubocop-rails
require: rubocop-rspec
require: rubocop-performance
require: rubocop-rake

AllCops:
  Exclude:
    - 'config/**/**'
    - 'config.ru'
    - 'Rakefile'
    - 'lib/**/**'
    - 'Gemfile.lock'
    - 'bin/**'
    - 'db/**/**'
    - 'app/helpers/**'
    - 'app/channels/**/**'
    - 'app/assets/**'
    - 'app/mailers/**'
    - 'spec/helpers/**'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'app/jobs/**'

Style/FrozenStringLiteralComment:
  Enabled: false
  
Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/**'
