require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/changes_histories', type: :request do
  # ChangesHistory. As you add validations to ChangesHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ChangesHistory.create! valid_attributes
      get changes_histories_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      changes_history = ChangesHistory.create! valid_attributes
      get changes_history_url(changes_history)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_changes_history_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      changes_history = ChangesHistory.create! valid_attributes
      get edit_changes_history_url(changes_history)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ChangesHistory' do
        expect do
          post changes_histories_url, params: { changes_history: valid_attributes }
        end.to change(ChangesHistory, :count).by(1)
      end

      it 'redirects to the created changes_history' do
        post changes_histories_url, params: { changes_history: valid_attributes }
        expect(response).to redirect_to(changes_history_url(ChangesHistory.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ChangesHistory' do
        expect do
          post changes_histories_url, params: { changes_history: invalid_attributes }
        end.to change(ChangesHistory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post changes_histories_url, params: { changes_history: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested changes_history' do
        changes_history = ChangesHistory.create! valid_attributes
        patch changes_history_url(changes_history), params: { changes_history: new_attributes }
        changes_history.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the changes_history' do
        changes_history = ChangesHistory.create! valid_attributes
        patch changes_history_url(changes_history), params: { changes_history: new_attributes }
        changes_history.reload
        expect(response).to redirect_to(changes_history_url(changes_history))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        changes_history = ChangesHistory.create! valid_attributes
        patch changes_history_url(changes_history), params: { changes_history: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested changes_history' do
      changes_history = ChangesHistory.create! valid_attributes
      expect do
        delete changes_history_url(changes_history)
      end.to change(ChangesHistory, :count).by(-1)
    end

    it 'redirects to the changes_histories list' do
      changes_history = ChangesHistory.create! valid_attributes
      delete changes_history_url(changes_history)
      expect(response).to redirect_to(changes_histories_url)
    end
  end
end
