require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/commercial_premises', type: :request do
  # CommercialPremise. As you add validations to CommercialPremise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      CommercialPremise.create! valid_attributes
      get commercial_premises_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      commercial_premise = CommercialPremise.create! valid_attributes
      get commercial_premise_url(commercial_premise)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_commercial_premise_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      commercial_premise = CommercialPremise.create! valid_attributes
      get edit_commercial_premise_url(commercial_premise)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new CommercialPremise' do
        expect do
          post commercial_premises_url, params: { commercial_premise: valid_attributes }
        end.to change(CommercialPremise, :count).by(1)
      end

      it 'redirects to the created commercial_premise' do
        post commercial_premises_url, params: { commercial_premise: valid_attributes }
        expect(response).to redirect_to(commercial_premise_url(CommercialPremise.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new CommercialPremise' do
        expect do
          post commercial_premises_url, params: { commercial_premise: invalid_attributes }
        end.to change(CommercialPremise, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post commercial_premises_url, params: { commercial_premise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested commercial_premise' do
        commercial_premise = CommercialPremise.create! valid_attributes
        patch commercial_premise_url(commercial_premise), params: { commercial_premise: new_attributes }
        commercial_premise.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the commercial_premise' do
        commercial_premise = CommercialPremise.create! valid_attributes
        patch commercial_premise_url(commercial_premise), params: { commercial_premise: new_attributes }
        commercial_premise.reload
        expect(response).to redirect_to(commercial_premise_url(commercial_premise))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        commercial_premise = CommercialPremise.create! valid_attributes
        patch commercial_premise_url(commercial_premise), params: { commercial_premise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested commercial_premise' do
      commercial_premise = CommercialPremise.create! valid_attributes
      expect do
        delete commercial_premise_url(commercial_premise)
      end.to change(CommercialPremise, :count).by(-1)
    end

    it 'redirects to the commercial_premises list' do
      commercial_premise = CommercialPremise.create! valid_attributes
      delete commercial_premise_url(commercial_premise)
      expect(response).to redirect_to(commercial_premises_url)
    end
  end
end
