require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/flats', type: :request do
  # Flat. As you add validations to Flat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Flat.create! valid_attributes
      get flats_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      flat = Flat.create! valid_attributes
      get flat_url(flat)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_flat_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      flat = Flat.create! valid_attributes
      get edit_flat_url(flat)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Flat' do
        expect do
          post flats_url, params: { flat: valid_attributes }
        end.to change(Flat, :count).by(1)
      end

      it 'redirects to the created flat' do
        post flats_url, params: { flat: valid_attributes }
        expect(response).to redirect_to(flat_url(Flat.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Flat' do
        expect do
          post flats_url, params: { flat: invalid_attributes }
        end.to change(Flat, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post flats_url, params: { flat: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested flat' do
        flat = Flat.create! valid_attributes
        patch flat_url(flat), params: { flat: new_attributes }
        flat.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the flat' do
        flat = Flat.create! valid_attributes
        patch flat_url(flat), params: { flat: new_attributes }
        flat.reload
        expect(response).to redirect_to(flat_url(flat))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        flat = Flat.create! valid_attributes
        patch flat_url(flat), params: { flat: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested flat' do
      flat = Flat.create! valid_attributes
      expect do
        delete flat_url(flat)
      end.to change(Flat, :count).by(-1)
    end

    it 'redirects to the flats list' do
      flat = Flat.create! valid_attributes
      delete flat_url(flat)
      expect(response).to redirect_to(flats_url)
    end
  end
end
