require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/renovations', type: :request do
  # Renovation. As you add validations to Renovation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Renovation.create! valid_attributes
      get renovations_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      renovation = Renovation.create! valid_attributes
      get renovation_url(renovation)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_renovation_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      renovation = Renovation.create! valid_attributes
      get edit_renovation_url(renovation)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Renovation' do
        expect do
          post renovations_url, params: { renovation: valid_attributes }
        end.to change(Renovation, :count).by(1)
      end

      it 'redirects to the created renovation' do
        post renovations_url, params: { renovation: valid_attributes }
        expect(response).to redirect_to(renovation_url(Renovation.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Renovation' do
        expect do
          post renovations_url, params: { renovation: invalid_attributes }
        end.to change(Renovation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post renovations_url, params: { renovation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested renovation' do
        renovation = Renovation.create! valid_attributes
        patch renovation_url(renovation), params: { renovation: new_attributes }
        renovation.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the renovation' do
        renovation = Renovation.create! valid_attributes
        patch renovation_url(renovation), params: { renovation: new_attributes }
        renovation.reload
        expect(response).to redirect_to(renovation_url(renovation))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        renovation = Renovation.create! valid_attributes
        patch renovation_url(renovation), params: { renovation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested renovation' do
      renovation = Renovation.create! valid_attributes
      expect do
        delete renovation_url(renovation)
      end.to change(Renovation, :count).by(-1)
    end

    it 'redirects to the renovations list' do
      renovation = Renovation.create! valid_attributes
      delete renovation_url(renovation)
      expect(response).to redirect_to(renovations_url)
    end
  end
end
