require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/streets', type: :request do
  # Street. As you add validations to Street, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Street.create! valid_attributes
      get streets_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      street = Street.create! valid_attributes
      get street_url(street)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_street_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      street = Street.create! valid_attributes
      get edit_street_url(street)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Street' do
        expect do
          post streets_url, params: { street: valid_attributes }
        end.to change(Street, :count).by(1)
      end

      it 'redirects to the created street' do
        post streets_url, params: { street: valid_attributes }
        expect(response).to redirect_to(street_url(Street.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Street' do
        expect do
          post streets_url, params: { street: invalid_attributes }
        end.to change(Street, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post streets_url, params: { street: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested street' do
        street = Street.create! valid_attributes
        patch street_url(street), params: { street: new_attributes }
        street.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the street' do
        street = Street.create! valid_attributes
        patch street_url(street), params: { street: new_attributes }
        street.reload
        expect(response).to redirect_to(street_url(street))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        street = Street.create! valid_attributes
        patch street_url(street), params: { street: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested street' do
      street = Street.create! valid_attributes
      expect do
        delete street_url(street)
      end.to change(Street, :count).by(-1)
    end

    it 'redirects to the streets list' do
      street = Street.create! valid_attributes
      delete street_url(street)
      expect(response).to redirect_to(streets_url)
    end
  end
end
