require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/user_infos', type: :request do
  # UserInfo. As you add validations to UserInfo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      UserInfo.create! valid_attributes
      get user_infos_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      user_info = UserInfo.create! valid_attributes
      get user_info_url(user_info)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_info_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      user_info = UserInfo.create! valid_attributes
      get edit_user_info_url(user_info)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new UserInfo' do
        expect do
          post user_infos_url, params: { user_info: valid_attributes }
        end.to change(UserInfo, :count).by(1)
      end

      it 'redirects to the created user_info' do
        post user_infos_url, params: { user_info: valid_attributes }
        expect(response).to redirect_to(user_info_url(UserInfo.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new UserInfo' do
        expect do
          post user_infos_url, params: { user_info: invalid_attributes }
        end.to change(UserInfo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_infos_url, params: { user_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested user_info' do
        user_info = UserInfo.create! valid_attributes
        patch user_info_url(user_info), params: { user_info: new_attributes }
        user_info.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the user_info' do
        user_info = UserInfo.create! valid_attributes
        patch user_info_url(user_info), params: { user_info: new_attributes }
        user_info.reload
        expect(response).to redirect_to(user_info_url(user_info))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_info = UserInfo.create! valid_attributes
        patch user_info_url(user_info), params: { user_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested user_info' do
      user_info = UserInfo.create! valid_attributes
      expect do
        delete user_info_url(user_info)
      end.to change(UserInfo, :count).by(-1)
    end

    it 'redirects to the user_infos list' do
      user_info = UserInfo.create! valid_attributes
      delete user_info_url(user_info)
      expect(response).to redirect_to(user_infos_url)
    end
  end
end
